notifications:
  email: false

os: linux
dist: xenial
language: python
python:
  - "3.6"
  - "2.7"

install: pip install -r requirements.txt
script:
  - pip install pytest~=3.6.1 pytest-cov~=2.4
  - pytest --cov=geodesic

jobs:
  include:
    - stage: lint
      install: pip install flake8
      script:
        - pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        - flake8 . --exit-zero
